var locators = require('../utils/locators.js')
var common = require('../utils/common.js')
mob.transaction("init")
common.StartApp()
mob.transaction("Waiting for login Page to load")
mob.waitForVisible(locators.loginPage.loginButton)
mob.transaction("Typing userName")
mob.type(locators.loginPage.userName, "sgv usuario 7")
mob.transaction("Typing password")
mob.type(locators.loginPage.password, "Orgullo07")
mob.transaction("Typing clicking on LoginButton")
mob.click(locators.loginPage.loginButton)
mob.transaction("Waiting for Pin Page to load")
mob.waitForVisible(locators.pinPage.number1)
mob.transaction("Configure Pin")
mob.clickMultipleTimes(
    "//*[@text='1']",
    8)
mob.transaction("Waiting for Home Page to load")
mob.waitForVisible(locators.homePage.refresh)
